name: CI
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
permissions:
  contents: read

jobs:
  golangci:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.64.6

  build:
    name: Build Source
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.21]
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check out source
        uses: actions/checkout@v2
      - name: Build
        run: make build-src

  unittest:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.21]
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check out source
        uses: actions/checkout@v2
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-replica-set: replicaset
      - name: Unit test
        env:
          MONGODB_TEST_CXN: mongodb://localhost:27017
        run: make test-ci

  servermem:
    name: Server MemoryStore Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.21]
        fix-version:
          - fix40
          - fix41
          - fix42
          - fix43
          - fix44
          - fix50
          - fix50sp1
          - fix50sp2
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check out source
        uses: actions/checkout@v2
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Acceptance test
        env:
          GO111MODULE: on
          FIX_TEST: ${{ matrix.fix-version }}
          STORE_TYPE: memory
          ACCEPTANCE_SET: server
        run: make generate-ci && make build && make $FIX_TEST
      - name: Acceptance test with udecimal
        env:
          GO111MODULE: on
          FIX_TEST: ${{ matrix.fix-version }}
          STORE_TYPE: memory
          ACCEPTANCE_SET: server
        run: make generate-ci-udecimal && make build && make $FIX_TEST

  serverfile:
    name: Server FileStore Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.21]
        fix-version:
          - fix40
          - fix41
          - fix42
          - fix43
          - fix44
          - fix50
          - fix50sp1
          - fix50sp2
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check out source
        uses: actions/checkout@v2
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Acceptance test
        env:
          GO111MODULE: on
          FIX_TEST: ${{ matrix.fix-version }}
          STORE_TYPE: file
          ACCEPTANCE_SET: server
        run: make generate-ci && make build && make $FIX_TEST
      - name: Acceptance test with udecimal
        env:
          GO111MODULE: on
          FIX_TEST: ${{ matrix.fix-version }}
          STORE_TYPE: file
          ACCEPTANCE_SET: server
        run: make generate-ci-udecimal && make build && make $FIX_TEST

  servermongo:
    name: Server MongoStore Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.21]
        fix-version:
          - fix40
          - fix41
          - fix42
          - fix43
          - fix44
          - fix50
          - fix50sp1
          - fix50sp2
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check out source
        uses: actions/checkout@v2
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-replica-set: replicaset
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Acceptance test
        env:
          GO111MODULE: on
          MONGODB_TEST_CXN: mongodb://localhost:27017
          FIX_TEST: ${{ matrix.fix-version }}
          STORE_TYPE: mongo
          ACCEPTANCE_SET: server
        run: make generate-ci && make build && make $FIX_TEST
      - name: Acceptance test with udecimal
        env:
          GO111MODULE: on
          FIX_TEST: ${{ matrix.fix-version }}
          STORE_TYPE: mongo
          ACCEPTANCE_SET: server
        run: make generate-ci-udecimal && make build && make $FIX_TEST

  resendreqchunksize:
    name: ResendRequestChunkSize Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.21]
        fix-version:
          - fix40
          - fix41
          - fix42
          - fix43
          - fix44
          - fix50
          - fix50sp1
          - fix50sp2
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check out source
        uses: actions/checkout@v2
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Acceptance test
        env:
          GO111MODULE: on
          FIX_TEST: ${{ matrix.fix-version }}
          STORE_TYPE: memory
          ACCEPTANCE_SET: resendreqchunksize
        run: make generate-ci && make build && make $FIX_TEST
      - name: Acceptance test with udecimal
        env:
          GO111MODULE: on
          FIX_TEST: ${{ matrix.fix-version }}
          STORE_TYPE: memory
          ACCEPTANCE_SET: resendreqchunksize
        run: make generate-ci-udecimal && make build && make $FIX_TEST

  lastseqnumprocessed:
    name: LastSeqNumProcessed Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.21]
        fix-version:
          - fix42
          - fix43
          - fix44
          - fix50
          - fix50sp1
          - fix50sp2
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check out source
        uses: actions/checkout@v2
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Acceptance test
        env:
          GO111MODULE: on
          FIX_TEST: ${{ matrix.fix-version }}
          STORE_TYPE: memory
          ACCEPTANCE_SET: lastseqnumprocessed
        run: make generate-ci && make build && make $FIX_TEST
      - name: Acceptance test with udecimal
        env:
          GO111MODULE: on
          FIX_TEST: ${{ matrix.fix-version }}
          STORE_TYPE: memory
          ACCEPTANCE_SET: lastseqnumprocessed
        run: make generate-ci-udecimal && make build && make $FIX_TEST

  nextexpectedseqnum:
    name: NextExpectedSeqNum Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.21]
        fix-version:
          - fix44
          - fix50
          - fix50sp1
          - fix50sp2
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check out source
        uses: actions/checkout@v2
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Acceptance test
        env:
          GO111MODULE: on
          FIX_TEST: ${{ matrix.fix-version }}
          STORE_TYPE: memory
          ACCEPTANCE_SET: nextexpectedseqnum
        run: make generate-ci && make build && make $FIX_TEST
      - name: Acceptance test with udecimal
        env:
          GO111MODULE: on
          FIX_TEST: ${{ matrix.fix-version }}
          STORE_TYPE: memory
          ACCEPTANCE_SET: nextexpectedseqnum
        run: make generate-ci-udecimal && make build && make $FIX_TEST
